package main

import (
	"context"
	stdlog "log"

	box "github.com/sagernet/sing-box"
	"github.com/sagernet/sing-box/experimental/deprecated"
	"github.com/sagernet/sing-box/include"
	sblog "github.com/sagernet/sing-box/log"
	"github.com/sagernet/sing-box/option"
	"github.com/sagernet/sing/common/json"
	"github.com/sagernet/sing/service"
)

func appendJSONList(target []any, value any) []any {
	switch typed := value.(type) {
	case []any:
		return append(target, typed...)
	case string:
		if typed != "" {
			return append(target, typed)
		}
	}
	return target
}

// normalizeLegacyConfig keeps configurations generated by older NekoRay
// builds usable with sing-box 1.13. The removed inbound fields are expressed
// as route actions, old TUN address fields are merged, and the removed DNS
// outbound is replaced with the hijack-dns action.
func normalizeLegacyConfig(configContent []byte) ([]byte, error) {
	config, err := json.UnmarshalExtended[map[string]any](configContent)
	if err != nil {
		return nil, err
	}

	changed := false
	var inboundActions []any
	if inbounds, loaded := config["inbounds"].([]any); loaded {
		for _, rawInbound := range inbounds {
			inbound, loaded := rawInbound.(map[string]any)
			if !loaded {
				continue
			}
			tag, _ := inbound["tag"].(string)
			domainStrategy, hasDomainStrategy := inbound["domain_strategy"].(string)
			sniff, hasSniff := inbound["sniff"].(bool)
			sniffTimeout, _ := inbound["sniff_timeout"].(string)
			udpDisableDomainUnmapping, hasUDPDisableDomainUnmapping := inbound["udp_disable_domain_unmapping"].(bool)

			for _, field := range []string{"domain_strategy", "sniff", "sniff_override_destination", "sniff_timeout", "udp_disable_domain_unmapping", "proxy_protocol", "proxy_protocol_accept_no_header"} {
				if _, exists := inbound[field]; exists {
					delete(inbound, field)
					changed = true
				}
			}

			if inbound["type"] == "tun" {
				for target, legacyFields := range map[string][]string{
					"address":               {"inet4_address", "inet6_address"},
					"route_address":         {"inet4_route_address", "inet6_route_address"},
					"route_exclude_address": {"inet4_route_exclude_address", "inet6_route_exclude_address"},
				} {
					values := appendJSONList(nil, inbound[target])
					for _, legacyField := range legacyFields {
						if legacyValue, exists := inbound[legacyField]; exists {
							values = appendJSONList(values, legacyValue)
							delete(inbound, legacyField)
							changed = true
						}
					}
					if len(values) > 0 {
						inbound[target] = values
					}
				}
				for _, field := range []string{"endpoint_independent_nat", "gso"} {
					if _, exists := inbound[field]; exists {
						delete(inbound, field)
						changed = true
					}
				}
			}

			if tag == "" {
				continue
			}
			if hasDomainStrategy && domainStrategy != "" && domainStrategy != "AsIs" {
				inboundActions = append(inboundActions, map[string]any{
					"inbound":  tag,
					"action":   "resolve",
					"strategy": domainStrategy,
				})
			}
			if hasSniff && sniff {
				action := map[string]any{"inbound": tag, "action": "sniff"}
				if sniffTimeout != "" {
					action["timeout"] = sniffTimeout
				}
				inboundActions = append(inboundActions, action)
			}
			if hasUDPDisableDomainUnmapping && udpDisableDomainUnmapping {
				inboundActions = append(inboundActions, map[string]any{
					"inbound":                      tag,
					"action":                       "route-options",
					"udp_disable_domain_unmapping": true,
				})
			}
		}
	}

	dnsOutboundTags := make(map[string]bool)
	emptyDirectOutboundTags := make(map[string]bool)
	if outbounds, loaded := config["outbounds"].([]any); loaded {
		filtered := make([]any, 0, len(outbounds))
		for _, rawOutbound := range outbounds {
			outbound, loaded := rawOutbound.(map[string]any)
			if loaded && outbound["type"] == "direct" && len(outbound) == 2 {
				if tag, isString := outbound["tag"].(string); isString {
					emptyDirectOutboundTags[tag] = true
				}
			}
			if loaded && outbound["type"] == "dns" {
				if tag, isString := outbound["tag"].(string); isString {
					dnsOutboundTags[tag] = true
				}
				changed = true
				continue
			}
			filtered = append(filtered, rawOutbound)
		}
		config["outbounds"] = filtered
	}

	// sing-box 1.13 rejects a DNS detour that points to an otherwise empty
	// direct outbound. Removing the detour preserves the same direct path.
	if dns, loaded := config["dns"].(map[string]any); loaded {
		if servers, loaded := dns["servers"].([]any); loaded {
			for _, rawServer := range servers {
				server, loaded := rawServer.(map[string]any)
				if !loaded {
					continue
				}
				detour, _ := server["detour"].(string)
				if emptyDirectOutboundTags[detour] {
					delete(server, "detour")
					changed = true
				}
			}
		}
	}

	route, _ := config["route"].(map[string]any)
	if route == nil && (len(inboundActions) > 0 || len(dnsOutboundTags) > 0) {
		route = make(map[string]any)
		config["route"] = route
	}
	if route != nil {
		rules, _ := route["rules"].([]any)
		for _, rawRule := range rules {
			rule, loaded := rawRule.(map[string]any)
			if !loaded {
				continue
			}
			outbound, _ := rule["outbound"].(string)
			if dnsOutboundTags[outbound] {
				delete(rule, "outbound")
				rule["action"] = "hijack-dns"
				changed = true
			}
		}
		if len(inboundActions) > 0 {
			route["rules"] = append(inboundActions, rules...)
		}
	}

	if !changed {
		return configContent, nil
	}
	return json.Marshal(config)
}

func createAndStartBox(configContent []byte, disableColor bool) (*box.Box, context.CancelFunc, error) {
	stdlog.Println("createAndStartBox: parse config")
	baseCtx := context.Background()
	baseCtx = include.Context(service.ContextWith(baseCtx, deprecated.NewStderrManager(sblog.StdLogger())))
	configContent, err := normalizeLegacyConfig(configContent)
	if err != nil {
		stdlog.Println("createAndStartBox: normalize config failed:", err)
		return nil, nil, err
	}

	options, err := json.UnmarshalExtendedContext[option.Options](baseCtx, configContent)
	if err != nil {
		stdlog.Println("createAndStartBox: parse config failed:", err)
		return nil, nil, err
	}
	stdlog.Println("createAndStartBox: parse config done")
	if disableColor {
		if options.Log == nil {
			options.Log = &option.LogOptions{}
		}
		options.Log.DisableColor = true
	}

	stdlog.Println("createAndStartBox: box.New")
	ctx, cancel := context.WithCancel(baseCtx)
	instance, err := box.New(box.Options{
		Context: ctx,
		Options: options,
	})
	if err != nil {
		stdlog.Println("createAndStartBox: box.New failed:", err)
		cancel()
		return nil, nil, err
	}
	stdlog.Println("createAndStartBox: box.New done")
	stdlog.Println("createAndStartBox: instance.Start")
	if err = instance.Start(); err != nil {
		stdlog.Println("createAndStartBox: instance.Start failed:", err)
		cancel()
		_ = instance.Close()
		return nil, nil, err
	}
	stdlog.Println("createAndStartBox: instance.Start done")
	return instance, cancel, nil
}
